permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js]



title: "LeenShine"
email: "yanping.li@qq.com"
description: "Test Engineer"
github_username:  "LeenShine"



url: "http://leenshine.huangyan800.com"
#imgrepo: "http://blog.rainyalley.com/static/img"



